name: flutter_ankidroid
description: A flutter wrapper over the java AnkiDroid API.
version: 0.8.1
repository: https://github.com/aaalkoud/flutter_ankidroid/

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.4
  async: ^2.11.0
  request_permission: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aaalkoud.flutter_ankidroid
        pluginClass: FlutterAnkidroidPlugin
